pub mod agent_markdown_renderer;
pub mod agent_title;
pub mod agent_toolbox;
pub mod codex_oauth;
pub mod compact;
pub mod config;
mod context_usage;
pub mod diag;
mod edb_migration;
pub mod event;
pub mod gateway;
pub mod gateway_process;
pub mod gateway_settings;
pub mod gateway_state;
pub mod gateway_webui;
pub mod image_toolbox;
pub mod managed_child;
pub mod managed_protocol;
pub mod markdown;
pub mod model;
pub mod model_transfer;
pub mod orchestrator;
mod python_runtime;
pub mod terminal;
pub mod termination;
mod tool_result_truncation;
pub mod toolbox;
pub mod tui;
mod turn_history;
pub mod ui_backend;
pub mod updater;
pub mod web_auth;
pub mod webui;
pub mod workmap;
pub mod workspace;
pub mod workspace_bootstrap;

pub type Result<T> = std::result::Result<T, Box<dyn std::error::Error + Send + Sync>>;
